global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'local-docker'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'backend-service'
    static_configs:
      - targets: ['backend:3000']
    metrics_path: '/metrics'
